// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbysjvZSvrHyEg45qclwDZ6QCKaGz2WWo',
    appId: '1:633272558603:web:2c2a2d31bef1131af9130e',
    messagingSenderId: '633272558603',
    projectId: 'addu-pestdetector',
    authDomain: 'addu-pestdetector.firebaseapp.com',
    storageBucket: 'addu-pestdetector.firebasestorage.app',
    measurementId: 'G-9406RMD04L',
  );

  // ================= WEB =================

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBrukGu5BMpbujLTEKaHryF1kbSPbm6IM',
    appId: '1:633272558603:android:97294949f4bb1ce1f9130e',
    messagingSenderId: '633272558603',
    projectId: 'addu-pestdetector',
    storageBucket: 'addu-pestdetector.firebasestorage.app',
  );

  // ================= ANDROID =================

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAbLuTeDNpscDvmAIRQ-gu702yjyL_JmM',
    appId: '1:633272558603:ios:80d34e5ab713abfdf9130e',
    messagingSenderId: '633272558603',
    projectId: 'addu-pestdetector',
    storageBucket: 'addu-pestdetector.firebasestorage.app',
    androidClientId: '633272558603-3be2doklu107527s5nocmkkde59vd7o1.apps.googleusercontent.com',
    iosClientId: '633272558603-pguncl2haq9edss7a8r85e9fj2otr8ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.adduPestDetectorWeb',
  );

  // ================= IOS =================

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbysjvZSvrHyEg45qclwDZ6QCKaGz2WWo',
    appId: '1:633272558603:web:7b75a9d6a7fbc8f7f9130e',
    messagingSenderId: '633272558603',
    projectId: 'addu-pestdetector',
    authDomain: 'addu-pestdetector.firebaseapp.com',
    storageBucket: 'addu-pestdetector.firebasestorage.app',
    measurementId: 'G-8ZB7JJ5L7T',
  );

  // ================= WINDOWS =================

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAbLuTeDNpscDvmAIRQ-gu702yjyL_JmM',
    appId: '1:633272558603:ios:80d34e5ab713abfdf9130e',
    messagingSenderId: '633272558603',
    projectId: 'addu-pestdetector',
    storageBucket: 'addu-pestdetector.firebasestorage.app',
    androidClientId: '633272558603-3be2doklu107527s5nocmkkde59vd7o1.apps.googleusercontent.com',
    iosClientId: '633272558603-pguncl2haq9edss7a8r85e9fj2otr8ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.adduPestDetectorWeb',
  );

  // ================= MACOS =================
}